### ISSUE TITLE
Configuration options for executable

### ISSUE THREAD

**Issue by fredrikekre** [kdheepak/nvim-dap-julia#1]
I want to be able to configure the julia command:
https://github.com/kdheepak/nvim-dap-julia/blob/1dde5e70e242d3cfe18335e3b408a70bab8b0a8e/lua/nvim-dap-julia.lua#L35
and the environment used to load DebugAdapter:
https://github.com/kdheepak/nvim-dap-julia/blob/1dde5e70e242d3cfe18335e3b408a70bab8b0a8e/lua/nvim-dap-julia.lua#L36

**Comment by kdheepak** [comment]
Resolved in https://github.com/kdheepak/nvim-dap-julia/commit/94dfcae701b60d8479adabae46242f4b2b9efc9f

**Comment by fredrikekre** [comment]
Thanks!
